log_level: ERROR
hash: sha256
shards:
  - path: ./share/raw/shard1
    range:
    - 00
    - 7f
    capacity: 1073741824 # 1 GB
  - path: ./share/raw/shard2
    range:
    - 80
    - ff
    capacity: 536870912 # 512 MB
